version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hospital-db
    environment:
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/hospital
    container_name: hospital-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hospital_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    build: ./frontend/hospital-management-frontend
    container_name: hospital-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
